config/routes.rb
Rails.application.routes.draw do
  devise_for :users



  namespace :admin do
    resources :disasters
  end

  resources :posts, param: :serial_number do
    resources :comments
  end

  get '/:short_url' => 'posts#redirect'
  root 'posts#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  require 'carrierwave/orm/activerecord'
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :content

  belongs_to :post
  belongs_to :user
end

app/models/disaster.rb
class Disaster < ApplicationRecord
  validates_presence_of :category
  has_many :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :content
  has_many :comments
  belongs_to :user
  belongs_to :disaster

  mount_uploader :image, ImageUploader


  before_create :generate_unique_number
  after_commit :generate_serial_number

  def generate_unique_number
    loop do
      @short = rand(0..9999).to_s.rjust(4, '0')
      break unless Post.exists?(short_url: @short)
    end
    self.short_url = @short
  end

  def generate_serial_number
    # count_post_today = Post.where(created_at: DateTime.current.beginning_of_day..DateTime.current.end_of_day).count
    # self.update(serial_number: "#{Date.current.strftime('%y%m%d')}#{count_post_today.to_s.rjust(4, '0')}")
    ActiveRecord::Base.connection.execute("UPDATE `posts` SET `posts`.`serial_number` = CONCAT(DATE_FORMAT(CONVERT_TZ(posts.created_at, '+00:00', '+8:00'), '%y%m%d'),
                                                      (SELECT LPAD(count(*), 6, 0)
                                                       FROM `posts` where `posts`.`id` <= #{id} and DATE(CONVERT_TZ(posts.created_at, '+00:00', '+8:00')) = (select DATE(CONVERT_TZ(posts.created_at, '+00:00', '+8:00'))
                                                       FROM posts WHERE posts.id = #{id})))
                                                       WHERE posts.id = #{id}")
  end

  def to_param  # overridden
    self.serial_number
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments
  has_many :posts

  def client?
    role == 'client'
  end

  def admin?
    role == 'admin'
  end

end

app/controllers/admin/disasters_controller.rb
class Admin::DisastersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin
  before_action :set_disaster, only: [:edit, :update, :destroy]


  def index
    @disasters = Disaster.all
  end

  def new
    @disaster = Disaster.new
  end

  def edit; end

  def update
    if @disaster.update(disaster_params)
      redirect_to admin_disasters_path
    else
      render :edit
    end
  end

  def destroy
    if @disaster.post.size.zero?
      @disaster.destroy
    else
      flash[:notice] = "this disaster type is currently in use in a post"
    end
    redirect_to admin_disasters_path
  end

  def create
    @disaster = Disaster.new(disaster_params)
    if @disaster.save
      redirect_to admin_disasters_path
    else
      render :new
    end
  end

  def check_admin
    unless current_user.admin?
      flash[:notice] = "You do not have permission"
      redirect_to posts_path
    end
  end

  def disaster_params
    params.require(:disaster).permit(:category)
  end

  def set_disaster
    @disaster = Disaster.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_post
  before_action :set_own_comment, only: [:edit, :update, :destroy]


  def index
    @comments = @post.comments.includes(:user)
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.post = @post
    @comment.user = current_user
    if @comment.save
      redirect_to post_comments_path(@post)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @comment.update(comment_params)
      redirect_to post_comments_path(@post, @comment)
    else
      render :edit
    end
  end

  def destroy
    if @comment.destroy
      redirect_to post_comments_path(@post)
    end
  end

  private

  def set_own_comment
    @comment = current_user.comments.find_by(id: params[:id])
    if @comment.nil?
      flash[:alert] = 'this post not belongs_to you or not exists'
      redirect_to post_comments_path
    end
  end

  def set_post
    @post = Post.find_by(serial_number: params[:serial_number])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_post, only: :show
  before_action :set_own_post, only: [:edit, :update, :destroy]
  require 'open-uri'

  def index
    @posts = Post.left_joins(:comments).group(:id).order('COUNT(comments.id) DESC').includes(:user, :disaster)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    # for non-developer:
    # @post.ip = request.remote_ip
    @post.ip = open('http://whatismyip.akamai.com').read
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def show; end

  def destroy
    if @post.comments.size.zero?
      @post.destroy
    else
      flash[:notice] = "this post has comments you can't delete it"
    end
    redirect_to posts_path
  end

  def redirect
    @short = params[:short_url]
    @url = Post.find_by(short_url: @short)
    if @url.nil? #if 404
      content_not_found
    else
      redirect_to post_path(@url)
    end
  end

  private

  def set_own_post
    @post = current_user.posts.find_by(serial_number: params[:serial_number])
    if @post.nil?
      flash[:alert] = 'this post not belongs_to you or not exists'
      redirect_to posts_path
    end
  end

  def post_params
    params.require(:post).permit(:title, :content, :address, :image, :disaster_id)
  end

  def set_post
    @post = Post.find_by(serial_number: params[:serial_number])
  end

  def content_not_found
    render :file => "#{Rails.root}/public/404.html", layout: false, status: :not_found
  end

end

app/helpers/admin/disasters_helper.rb
module Admin::DisastersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/disasters/edit.html.erb
<h1>Edit Disaster id: <%= @disaster.id %></h1>
<%= link_to 'back', admin_disasters_path, class: 'btn btn-danger' %>
<%= form_for @disaster, url: admin_disaster_path(@disaster), method: :patch do |f| %>
  <%= f.label :category %>
  <%= f.text_field :category %>
  <%= f.submit 'Update', class: 'btn btn-success' %>
<% end %>

app/views/admin/disasters/index.html.erb
<%= link_to 'Back to post', posts_path, class: 'btn btn-warning'%>
<%= link_to "Logout", destroy_user_session_path, :method => :delete, class:"btn btn-warning float-right" %>

<h1>Disaster type</h1>
<table class="table table-striped table-hover">
  <thead>
  <th>Id</th>
  <th>Type</th>
  <th>Action</th>
  </thead>
  <tbody>
  <% @disasters.each do |disaster| %>
    <tr>
      <td><%= disaster.id %></td>
      <td><%= disaster.category %></td>
      <td><%= link_to 'edit', edit_admin_disaster_path(disaster), class: 'btn btn-warning' %>
        <%= button_to "delete", admin_disaster_path(disaster), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'New', new_admin_disaster_path, class: 'btn btn-success' %>

app/views/admin/disasters/new.html.erb
<h1>New Disaster type<%= @disaster.id %></h1>
<% if @disaster.errors.any? %>
  <% @disaster.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
<% end %>
<%= form_for @disaster, url: admin_disasters_path(@disaster), method: :post do |f| %>
  <%= f.label :category %>
  <%= f.text_field :category %>
  <%= f.submit %>
<% end %>
<%= link_to 'back', admin_disasters_path %>

app/views/comments/edit.html.erb
<h1>Edit Post id: <%= @post.id %>, Comment ID:<%= @comment.id %></h1>

<%= form_for @comment, url: post_comment_path(@post, @comment), method: :patch do |f| %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

app/views/comments/index.html.erb
<h1><%= @post.id %></h1>
<%= link_to 'back to posts index', posts_path, class: "btn btn-danger" %>
<div class="card" style="width: 18rem;">
  <div class="card-header"><%= @post.title %></div>
  <%= image_tag "#{request.base_url}#{@post.image.url}", class:"card-img-top" if @post.image? %>
  <div class="card-body">
    <span class="badge bg-warning">
       <%= @post.disaster.category %>
    </span>
    <p class="card-text"><%= @post.content %></p>
    <p class="card-text"><small class="text-muted">created by: <%= @post.user.email %></small></p>
  </div>
</div>
<%unless @comments.size.zero?%>
  <h3>Comments</h3>
  <table class="table">
    <thead>
    <th>id</th>
    <th>creator</th>
    <th>content</th>
    <th>action</th>
    </thead>
    <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.id %></td>
        <td><%= comment.user.email %></td>
        <td><%= comment.content %></td>
        <td>
          <% if comment.user == current_user %>
            <%= link_to 'edit', edit_post_comment_path(@post, comment), class: "btn btn-warning" %>
            <%= button_to "delete", post_comment_path(@post, comment), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div>no comment to show</div>
<% end %>

<%= link_to 'new comment', new_post_comment_path(@post), class: "btn btn-success" %>

app/views/comments/new.html.erb
<h1>New comment for Post id <%= @post.id %></h1>

<% if @comment.errors.any? %>
  <% @comment.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
<% end %>
<%= form_for @comment, url: post_comments_path(@post), method: :post do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content, class: 'input-field' %>
  <%= f.submit 'Post', class: 'btn btn-success' %>
<% end %>

<%= link_to 'back', post_comments_path, class: 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Warning !! ensure that "stylesheet_pack_tag" is used, line below -->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid" style="padding:4px">
    <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<% if post.errors.any? %>
  <% post.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
<% end %>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :content %>
  <%= f.text_area :content, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :address %>
  <%= f.text_field :address, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :image %>
  <%= f.file_field :image, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :disaster %>
  <%= f.collection_select :disaster_id, Disaster.order(:category), :id, :category, {:include_blank => true}, {class: "form-control"} %>
</div>
<div class="form-group">
  <%= f.submit class: 'btn btn-success' %>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post Id: <%= @post.id %></h1>
<%= link_to 'back to index', posts_path, class:"btn btn-danger" %>
<%= form_for @post, url: post_path(@post), method: :patch do |f| %>
  <%= render partial: 'form', locals: {f: f, post: @post} %>
<% end %>

app/views/posts/index.html.erb
<%= link_to 'Manage Disaster info', admin_disasters_path, class: 'btn btn-warning' if current_user&.admin? %>

<%= link_to "Log Out", destroy_user_session_path, :method => :delete, class: "btn btn-warning float-right" if current_user%>
<%= link_to "Log In", destroy_user_session_path, :method => :delete, class: "btn btn-success float-right" unless current_user%>
<h1>Post list</h1>



<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th scope="col">Rank</th>
    <th scope="col">ID</th>
    <th scope="col">Creator</th>
    <th scope="col">Title</th>
    <th scope="col">Content</th>
    <th scope="col">Address</th>
    <th scope="col">Disaster</th>
    <th scope="col">Short URL</th>
    <th scope="col">Serial Number</th>
    <th scope="col">Image</th>
    <th scope="col">Country posted</th>
    <th scope="col">ISP provider</th>
    <th scope="col">actions</th>

  </tr>
  </thead>
  <tbody>
  <% @posts.each_with_index do |post, index| %>
    <tr>
      <td><%= index + 1 %>
        <% if index < 3 %>
          <br>
          <span class="badge bg-danger">
              HOT
          </span>
        <% end %>
      </td>
      <td><%= post.id %></td>
      <td><%= post.user.email %></td>
      <td><%= post.title %></td>
      <td><%= post.content %></td>
      <td><%= post.address %></td>
      <td><%= post.disaster.category %></td>
      <td><%= link_to "#{request.base_url}/#{post.short_url}", "#{request.base_url}/#{post.short_url}", target: :_self %></td>
      <td><%= post.serial_number %></td>
      <td><%= image_tag "#{request.base_url}#{post.image.url}" if post.image? %></td>
      <td><%= Geocoder.search(post.ip).first&.country %></td>
      <td><%= Geocoder.search(post.ip).first&.data&.dig("org") %></td>
      <td>
        <%#= link_to :comments, post_comments_path(post), class: 'btn btn-info' %>
        <%= link_to "show", post_path(post), class: 'btn btn-primary' %>
        <%= link_to "edit", edit_post_path(post), class: 'btn btn-warning' if post.user == current_user %>
        <% if post.user == current_user %>
          <%= form_for post, url: post_path(post), method: :delete do |f| %>
            <%= f.submit 'delete', class: 'btn btn-danger' %>
          <% end %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'New', new_post_path, class: 'btn btn-success' %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= form_for @post, url: posts_path, method: :post do |f| %>
  <%= render partial: 'form', locals: {f: f, post: @post} %>
<% end %>

app/views/posts/show.html.erb
<h1>show post id <%= @post.id %></h1>
<ul>
  <li><%= @post.title %></li>
  <li><%= @post.content %></li>
</ul>
<%= link_to 'index', posts_path %>
<%= link_to 'edit', edit_post_path(@post) %>